export const deterrents = [
  "Why would you do that",
  "Maybe don't",
  "How about no",
  "Tomorrow maybe",
  "Good idea... NOT",
  "Better take a nap",
  "Or just do the opposite",
  "Era un domingo en la tarde y fui a los coches de choque",
  "Sounds like a nightmare",
  "No, you don't",
  "Really?",
  "Don't insist",
  "May I interest you in NO?",
  "Whoops, where did that go",
  "Open tiktok instead",
  "Watch Paddington 2 instead",
  "Haha, no",
  "Let's not",
  "Don't even try",
  "Dancing queeen, feel the beat from the tambourine oh yeah",
];
